data(mtcars)
print("LineCharts")
plot(mtcars)
print("DotPlot")
plot(mtcars$mpg, xlab = "Number of cars", ylab = "Miles per Gallon", col = "red")
print("BarPlot")
barplot(mtcars$hp, ylab = "HorsePower", col = "cyan", horiz = FALSE)
print("Histogram")
hist(mtcars$mpg,xlab = "Miles Per Gallon", main = "Histogram for MPG", col = "yellow")
print("BoxPlot")
boxplot(mtcars[,3:4])
print("ScatterPlot")
input <- mtcars[,c('wt','mpg')]
plot(x = input$wt,y = input$mpg,xlab = "Weight",ylab = "Milage",xlim = c(2.5,5),ylim = c(15,30),main = "Weight vs Milage")
print("KernalDensityPlot")
den = density(mtcars$mpg)
plot(den,main=" Kernel Density of Miles Per Gallon")
polygon(d, col="red", border="blue")
print("PieChart")
carb = table(mtcars$carb)
data.labels = names(carb)
share = round(carb/sum(carb)*100)
data.labels = paste(data.labels, share)
data.labels = paste(data.labels,"%",sep="") 
pie(carb,labels = data.labels,clockwise=TRUE, col=heat.colors(length(data.labels)), main="Frequency of Carb value")

