vec = sample(1:100,10)
cat("Sample: ",vec)
cat("\nMean: ",mean(vec))
cat("\nMedian: ",median(vec))
cat("\nVariance: ",var(vec))
cat("\nStandard Deviation: ",sd(vec))
cat("\nScale: ",scale(vec))
cat("\nSummary: ",summary(vec))
cat("\nRank: ",rank(vec))
cat("\nQuantile: ",quantile(vec))